# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('tema', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quali_tec', models.IntegerField(max_length=1)),
                ('inovacao', models.IntegerField(max_length=1)),
                ('resultado', models.IntegerField(max_length=1)),
                ('metodologia', models.IntegerField(max_length=1)),
                ('adeq_evento', models.IntegerField(max_length=1)),
                ('artigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento_app.Artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('tema', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=14)),
                ('tipo', models.CharField(choices=[('adm', 'ADMINISTRADOR'), ('aut', 'AUTOR'), ('avl', 'AVALIADOR')], max_length=3)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento_app.Evento')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento_app.Usuario'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento_app.Usuario'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento_app.Evento'),
        ),
    ]
